#!/usr/bin/env bash
# Use the 'ifconfig' commmand to display active IPv4 addresses on the machine
# 'grep -oP' extraccts IP addresses using a regular expression

ifconfig | grep -oP '(?<=inet\s)\d+(\.\d+){3}'